# **Weather Data Analysis Project**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("weather.csv")

In [ ]:
df.head(1)

        date  precipitation  temp_max  temp_min  wind  weather  avg_temp
0 2012-01-01            0.0      12.8       5.0   4.7  drizzle       8.9

In [ ]:
df.shape

(1461, 6)

In [ ]:
df.isnull().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
avg_temp         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: float64(4), object(2)
memory usage: 68.6+ KB

In [ ]:
df["date"] = pd.to_datetime(df["date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
 6   avg_temp       1461 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 80.0+ KB

## Average Temperature Calculation

In [ ]:
df["avg_temp"] = (df["temp_max"] + df["temp_min"]) / 2

In [ ]:
overall_avg_temp = df["avg_temp"].mean()
overall_avg_temp

np.float64(12.336926762491444)

## Detect Extreme Weather Days

In [ ]:
extreme_hot_days = df[df["temp_max"] > 35]
extreme_cold_days = df[df["temp_min"] < 5]

In [ ]:
print("Extreme Hot Days:", extreme_hot_days.shape[0])
print("Extreme Cold Days:", extreme_cold_days.shape[0])

Extreme Hot Days: 1
Extreme Cold Days: 385

## Summary

In [ ]:
df.describe()

,date,precipitation,temp_max,temp_min,wind,avg_temp
count,1461,1461.000000,1461.000000,1461.000000,1461.000000,1461.000000
mean,2013-12-31 00:00:00,3.029432,16.439083,8.234771,3.241136,12.336927
min,2012-01-01 00:00:00,0.000000,-1.600000,-7.100000,0.400000,-3.800000
25%,2012-12-31 00:00:00,0.000000,10.600000,4.400000,2.200000,7.750000
50%,2013-12-31 00:00:00,0.000000,15.600000,8.300000,3.000000,11.950000
75%,2014-12-31 00:00:00,2.800000,22.200000,12.200000,4.000000,17.200000
max,2015-12-31 00:00:00,55.900000,35.600000,18.300000,9.500000,26.700000
std,NaN,6.680194,7.349758,5.023004,1.437825,5.998051